### ISSUE TITLE
Feature request: recent tab/section

### ISSUE THREAD

**Issue by ff6347** [hfg-gmuend/openmoji-ios#6]
It would be great to have the recently used openmojis on top. In the stickers and in the app.

**Comment by b-g** [comment]
+1! Many thanks for the feedback!

**Comment by Sam0711er** [comment]
@ff6347 It took some time, but here it is: @ff6347

**Comment by b-g** [comment]
hi @Sam0711er, does this mean a new OpenMoji iOS App release is coming up? (that would be mega!)

**Comment by Sam0711er** [comment]
@b-g did you not see my imessage? ;)

**Comment by Sam0711er** [comment]
Added in Release v1.3 ✅
