### ISSUE TITLE
OpenMoji detail "share" view not showing on iPad (13.4.1)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-ios#9]
You can click an OpenMoji and the emoji will get the grey halo ... but then nothing happens and the app freezes :(

cc @Sam0711er

**Comment by anreji** [comment]
I have the same issue on a standard iPad (2019) and could "fix" it by using the app in splitscreen-mode.

**Comment by Sam0711er** [comment]
Fixed in v1.3 ✅
